INSERT INTO continents (continent) VALUES ('Europe');
INSERT INTO continents (continent) VALUES ('Asie');
INSERT INTO continents (continent) VALUES ('Amérique du Nord');
INSERT INTO continents (continent) VALUES ('Amérique du Sud');
INSERT INTO continents (continent) VALUES ('Océanie');
INSERT INTO continents (continent) VALUES ('Afrique');
INSERT INTO countries (country, continent_id) VALUES ('Algérie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Angola', 6);
INSERT INTO countries (country, continent_id) VALUES ('Bénin', 6);
INSERT INTO countries (country, continent_id) VALUES ('Botswana', 6);
INSERT INTO countries (country, continent_id) VALUES ('Burundi', 6);
INSERT INTO countries (country, continent_id) VALUES ('Cameroun', 6);
INSERT INTO countries (country, continent_id) VALUES ('République centrafricaine', 6);
INSERT INTO countries (country, continent_id) VALUES ('Tchad', 6);
INSERT INTO countries (country, continent_id) VALUES ('Comores', 6);
INSERT INTO countries (country, continent_id) VALUES ('Congo', 6);
INSERT INTO countries (country, continent_id) VALUES ('République Démocratique du Congo', 6);
INSERT INTO countries (country, continent_id) VALUES ('Djibouti', 6);
INSERT INTO countries (country, continent_id) VALUES ('Egypte', 6);
INSERT INTO countries (country, continent_id) VALUES ('Guinée-équatoriale', 6);
INSERT INTO countries (country, continent_id) VALUES ('Erythrée', 6);
INSERT INTO countries (country, continent_id) VALUES ('Ethiopie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Gabon', 6);
INSERT INTO countries (country, continent_id) VALUES ('Gambie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Ghana', 6);
INSERT INTO countries (country, continent_id) VALUES ('Guinée', 6);
INSERT INTO countries (country, continent_id) VALUES ('Guinée-Bissau', 6);
INSERT INTO countries (country, continent_id) VALUES ('Kenya', 6);
INSERT INTO countries (country, continent_id) VALUES ('Lesotho', 6);
INSERT INTO countries (country, continent_id) VALUES ('Liberia', 6);
INSERT INTO countries (country, continent_id) VALUES ('Libye', 6);
INSERT INTO countries (country, continent_id) VALUES ('Madagascar', 6);
INSERT INTO countries (country, continent_id) VALUES ('Malawi', 6);
INSERT INTO countries (country, continent_id) VALUES ('Mali', 6);
INSERT INTO countries (country, continent_id) VALUES ('Mauritanie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Ile Maurice', 6);
INSERT INTO countries (country, continent_id) VALUES ('Maroc', 6);
INSERT INTO countries (country, continent_id) VALUES ('Mozambique', 6);
INSERT INTO countries (country, continent_id) VALUES ('Namibie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Niger', 6);
INSERT INTO countries (country, continent_id) VALUES ('Nigeria', 6);
INSERT INTO countries (country, continent_id) VALUES ('Rwanda', 6);
INSERT INTO countries (country, continent_id) VALUES ('Sao-Tomé-et-Principe', 6);
INSERT INTO countries (country, continent_id) VALUES ('Sénégal', 6);
INSERT INTO countries (country, continent_id) VALUES ('Seychelles', 6);
INSERT INTO countries (country, continent_id) VALUES ('Sierra Leone', 6);
INSERT INTO countries (country, continent_id) VALUES ('Somalie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Afrique du Sud', 6);
INSERT INTO countries (country, continent_id) VALUES ('Soudan du Sud', 6);
INSERT INTO countries (country, continent_id) VALUES ('Soudan', 6);
INSERT INTO countries (country, continent_id) VALUES ('Eswatini', 6);
INSERT INTO countries (country, continent_id) VALUES ('Tanzanie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Togo', 6);
INSERT INTO countries (country, continent_id) VALUES ('Tunisie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Ouganda', 6);
INSERT INTO countries (country, continent_id) VALUES ('Zambie', 6);
INSERT INTO countries (country, continent_id) VALUES ('Zimbabwe', 6);
INSERT INTO countries (country, continent_id) VALUES ('Afghanistan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Bahrein', 2);
INSERT INTO countries (country, continent_id) VALUES ('Bangladesh', 2);
INSERT INTO countries (country, continent_id) VALUES ('Bhoutan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Birmanie', 2);
INSERT INTO countries (country, continent_id) VALUES ('Cambodge', 2);
INSERT INTO countries (country, continent_id) VALUES ('Chine', 2);
INSERT INTO countries (country, continent_id) VALUES ('Hong Kong', 2);
INSERT INTO countries (country, continent_id) VALUES ('Inde', 2);
INSERT INTO countries (country, continent_id) VALUES ('Indonésie', 2);
INSERT INTO countries (country, continent_id) VALUES ('Iran', 2);
INSERT INTO countries (country, continent_id) VALUES ('Irak', 2);
INSERT INTO countries (country, continent_id) VALUES ('Israel', 2);
INSERT INTO countries (country, continent_id) VALUES ('Japon', 2);
INSERT INTO countries (country, continent_id) VALUES ('Jordanie', 2);
INSERT INTO countries (country, continent_id) VALUES ('Kazakhstan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Corée du Nord', 2);
INSERT INTO countries (country, continent_id) VALUES ('Corée du Sud', 2);
INSERT INTO countries (country, continent_id) VALUES ('Koweit', 2);
INSERT INTO countries (country, continent_id) VALUES ('Kirghizistan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Laos', 2);
INSERT INTO countries (country, continent_id) VALUES ('Liban', 2);
INSERT INTO countries (country, continent_id) VALUES ('Malaisie', 2);
INSERT INTO countries (country, continent_id) VALUES ('Maldives', 2);
INSERT INTO countries (country, continent_id) VALUES ('Mongolie', 2);
INSERT INTO countries (country, continent_id) VALUES ('Népal', 2);
INSERT INTO countries (country, continent_id) VALUES ('Oman', 2);
INSERT INTO countries (country, continent_id) VALUES ('Pakistan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Philippines', 2);
INSERT INTO countries (country, continent_id) VALUES ('Qatar', 2);
INSERT INTO countries (country, continent_id) VALUES ('Arabie Saoudite', 2);
INSERT INTO countries (country, continent_id) VALUES ('Singapour', 2);
INSERT INTO countries (country, continent_id) VALUES ('Sri Lanka', 2);
INSERT INTO countries (country, continent_id) VALUES ('Taiwan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Tadjikistan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Thailande', 2);
INSERT INTO countries (country, continent_id) VALUES ('Turquie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Turkménistan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Emirats arabes unis', 2);
INSERT INTO countries (country, continent_id) VALUES ('Ouzbékistan', 2);
INSERT INTO countries (country, continent_id) VALUES ('Yémen', 2);
INSERT INTO countries (country, continent_id) VALUES ('Albanie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Andorre', 1);
INSERT INTO countries (country, continent_id) VALUES ('Arménie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Autriche', 1);
INSERT INTO countries (country, continent_id) VALUES ('Azerbaidjan', 1);
INSERT INTO countries (country, continent_id) VALUES ('Biélorussie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Belgique', 1);
INSERT INTO countries (country, continent_id) VALUES ('Bosnie-Herzégovine', 1);
INSERT INTO countries (country, continent_id) VALUES ('Bulgarie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Croatie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Chypre', 1);
INSERT INTO countries (country, continent_id) VALUES ('Danemark', 1);
INSERT INTO countries (country, continent_id) VALUES ('Estonie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Finlande', 1);
INSERT INTO countries (country, continent_id) VALUES ('France', 1);
INSERT INTO countries (country, continent_id) VALUES ('Écosse', 1);
INSERT INTO countries (country, continent_id) VALUES ('Pays de Galles', 1);
INSERT INTO countries (country, continent_id) VALUES ('Angleterre', 1);
INSERT INTO countries (country, continent_id) VALUES ('Géorgie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Allemagne', 1);
INSERT INTO countries (country, continent_id) VALUES ('Gréce', 1);
INSERT INTO countries (country, continent_id) VALUES ('Hongrie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Islande', 1);
INSERT INTO countries (country, continent_id) VALUES ('Irlande', 1);
INSERT INTO countries (country, continent_id) VALUES ('Irlande du Nord', 1);
INSERT INTO countries (country, continent_id) VALUES ('Italie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Lettonie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Liechtenstein', 1);
INSERT INTO countries (country, continent_id) VALUES ('Lituanie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Luxembourg', 1);
INSERT INTO countries (country, continent_id) VALUES ('Macédoine', 1);
INSERT INTO countries (country, continent_id) VALUES ('Malte', 1);
INSERT INTO countries (country, continent_id) VALUES ('Moldavie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Monaco', 1);
INSERT INTO countries (country, continent_id) VALUES ('Monténégro', 1);
INSERT INTO countries (country, continent_id) VALUES ('Pays-Bas', 1);
INSERT INTO countries (country, continent_id) VALUES ('Norvége', 1);
INSERT INTO countries (country, continent_id) VALUES ('Pologne', 1);
INSERT INTO countries (country, continent_id) VALUES ('Portugal', 1);
INSERT INTO countries (country, continent_id) VALUES ('Roumanie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Saint-Marin', 1);
INSERT INTO countries (country, continent_id) VALUES ('Serbie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Slovaquie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Slovénie', 1);
INSERT INTO countries (country, continent_id) VALUES ('Espagne', 1);
INSERT INTO countries (country, continent_id) VALUES ('Suéde', 1);
INSERT INTO countries (country, continent_id) VALUES ('Suisse', 1);
INSERT INTO countries (country, continent_id) VALUES ('Ukraine', 1);
INSERT INTO countries (country, continent_id) VALUES ('Vatican', 1);
INSERT INTO countries (country, continent_id) VALUES ('Antigua-et-Barbuda', 3);
INSERT INTO countries (country, continent_id) VALUES ('Bahamas', 3);
INSERT INTO countries (country, continent_id) VALUES ('Barbade', 3);
INSERT INTO countries (country, continent_id) VALUES ('Belize', 3);
INSERT INTO countries (country, continent_id) VALUES ('Canada', 3);
INSERT INTO countries (country, continent_id) VALUES ('Costa Rica', 3);
INSERT INTO countries (country, continent_id) VALUES ('Cuba', 3);
INSERT INTO countries (country, continent_id) VALUES ('République dominicaine', 3);
INSERT INTO countries (country, continent_id) VALUES ('Salvador', 3);
INSERT INTO countries (country, continent_id) VALUES ('Grenade', 3);
INSERT INTO countries (country, continent_id) VALUES ('Guatemala', 3);
INSERT INTO countries (country, continent_id) VALUES ('Haéti', 3);
INSERT INTO countries (country, continent_id) VALUES ('Honduras', 3);
INSERT INTO countries (country, continent_id) VALUES ('Jamaique', 3);
INSERT INTO countries (country, continent_id) VALUES ('Mexique', 3);
INSERT INTO countries (country, continent_id) VALUES ('Nicaragua', 3);
INSERT INTO countries (country, continent_id) VALUES ('Panama', 3);
INSERT INTO countries (country, continent_id) VALUES ('Saint-Christophe-et-Niévès', 3);
INSERT INTO countries (country, continent_id) VALUES ('Sainte-Lucie', 3);
INSERT INTO countries (country, continent_id) VALUES ('Saint-Vincent-et-les-Grenadines', 3);
INSERT INTO countries (country, continent_id) VALUES ('Trinité et Tobago', 3);
INSERT INTO countries (country, continent_id) VALUES ('Australie', 5);
INSERT INTO countries (country, continent_id) VALUES ('Fidji', 5);
INSERT INTO countries (country, continent_id) VALUES ('Kiribati', 5);
INSERT INTO countries (country, continent_id) VALUES ('Iles Marshall', 5);
INSERT INTO countries (country, continent_id) VALUES ('Micronésie', 5);
INSERT INTO countries (country, continent_id) VALUES ('Nauru', 5);
INSERT INTO countries (country, continent_id) VALUES ('Nouvelle-Zélande', 5);
INSERT INTO countries (country, continent_id) VALUES ('Palaos', 5);
INSERT INTO countries (country, continent_id) VALUES ('Papouasie-Nouvelle-Guinée', 5);
INSERT INTO countries (country, continent_id) VALUES ('Samoa', 5);
INSERT INTO countries (country, continent_id) VALUES ('Iles Salomon', 5);
INSERT INTO countries (country, continent_id) VALUES ('Tonga', 5);
INSERT INTO countries (country, continent_id) VALUES ('Tuvalu', 5);
INSERT INTO countries (country, continent_id) VALUES ('Vanuatu', 5);
INSERT INTO countries (country, continent_id) VALUES ('Argentine', 4);
INSERT INTO countries (country, continent_id) VALUES ('Bolivie', 4);
INSERT INTO countries (country, continent_id) VALUES ('Brésil', 4);
INSERT INTO countries (country, continent_id) VALUES ('Chili', 4);
INSERT INTO countries (country, continent_id) VALUES ('Colombie', 4);
INSERT INTO countries (country, continent_id) VALUES ('Equateur', 4);
INSERT INTO countries (country, continent_id) VALUES ('Guyana', 4);
INSERT INTO countries (country, continent_id) VALUES ('Paraguay', 4);
INSERT INTO countries (country, continent_id) VALUES ('Pérou', 4);
INSERT INTO countries (country, continent_id) VALUES ('Suriname', 4);
INSERT INTO countries (country, continent_id) VALUES ('Uruguay', 4);
INSERT INTO countries (country, continent_id) VALUES ('Venezuela', 4);
